from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('user-login/', views.user_login, name='user_login'),
    path('user-register/', views.user_register, name='user_register'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('password-reset-sent/', views.password_reset_sent, name='password_reset_sent'),
    path('reset-password/<uidb64>/<token>/', views.reset_password, name='reset_password'),
    path('admin-forgot-password/', views.admin_forgot_password, name='admin_forgot_password'),
    path('admin-password-reset-sent/', views.admin_password_reset_sent, name='admin_password_reset_sent'),
    path('admin-reset-password/<uidb64>/<token>/', views.admin_reset_password, name='admin_reset_password'),
    
    path('gallery/', views.gallery, name='gallery'),
    path('offers/', views.offers, name='offers'),
    path('barber/<int:pk>/gallery/', views.barber_gallery, name='barber_gallery'),
    path('barber/<int:pk>/location/', views.barber_location, name='barber_location'),
    
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-gallery/', views.admin_gallery_list, name='admin_gallery_list'),
    path('admin-gallery/create/<int:barber_id>/', views.admin_gallery_create, name='admin_gallery_create'),
    path('admin-gallery/<int:pk>/edit/', views.admin_gallery_edit, name='admin_gallery_edit'),
    path('admin-gallery/<int:pk>/delete/', views.admin_gallery_delete, name='admin_gallery_delete'),
    path('admin-offers/', views.admin_offers_list, name='admin_offers_list'),
    path('admin-offers/create/', views.admin_offers_create, name='admin_offers_create'),
    path('admin-offers/<int:pk>/edit/', views.admin_offers_edit, name='admin_offers_edit'),
    path('admin-offers/<int:pk>/delete/', views.admin_offers_delete, name='admin_offers_delete'),
    path('admin-barbers/<int:barber_id>/location/', views.admin_barber_location, name='admin_barber_location'),
    path('admin-barbers/', views.admin_barber_list, name='admin_barber_list'),
    path('admin-barbers/create/', views.admin_barber_create, name='admin_barber_create'),
    path('admin-barbers/<int:pk>/edit/', views.admin_barber_edit, name='admin_barber_edit'),
    path('admin-barbers/<int:pk>/delete/', views.admin_barber_delete, name='admin_barber_delete'),
    path('admin-services/', views.admin_service_list, name='admin_service_list'),
    path('admin-services/create/', views.admin_service_create, name='admin_service_create'),
    path('admin-services/<int:pk>/edit/', views.admin_service_edit, name='admin_service_edit'),
    path('admin-services/<int:pk>/delete/', views.admin_service_delete, name='admin_service_delete'),
    path('admin-bookings/', views.admin_booking_list, name='admin_booking_list'),
    path('admin-bookings/<int:pk>/', views.admin_booking_detail, name='admin_booking_detail'),
    path('admin-bookings/<int:pk>/update/', views.admin_booking_update, name='admin_booking_update'),
    path('admin-bookings/<int:pk>/delete/', views.admin_booking_delete, name='admin_booking_delete'),
    
    path('user-dashboard/', views.user_dashboard, name='user_dashboard'),
    path('user-barbers/', views.user_barber_list, name='user_barber_list'),
    path('user-barbers/<int:pk>/', views.user_barber_detail, name='user_barber_detail'),
    path('user-services/', views.user_service_list, name='user_service_list'),
    path('user-bookings/', views.user_booking_list, name='user_booking_list'),
    path('user-bookings/create/', views.user_booking_create, name='user_booking_create'),
    path('user-bookings/<int:pk>/', views.user_booking_detail, name='user_booking_detail'),
    path('user-bookings/<int:pk>/update/', views.user_booking_update, name='user_booking_update'),
    path('user-bookings/<int:pk>/cancel/', views.user_booking_cancel, name='user_booking_cancel'),
    path('user-bookings/<int:booking_id>/review/', views.user_add_review, name='user_add_review'),
    path('user-profile/', views.user_profile, name='user_profile'),
    path('user-profile/edit/', views.user_profile_edit, name='user_profile_edit'),
]
