# Generated by Django 4.2.7 on 2026-03-01 05:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'Regular User')], default='user', help_text='User role: admin or user', max_length=10)),
                ('phone', models.CharField(blank=True, help_text='User phone number', max_length=15)),
                ('dateofbirth', models.DateField(blank=True, help_text='User date of birth', null=True)),
                ('address', models.TextField(blank=True, help_text='User address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Barber full name', max_length=100)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('bio', models.TextField(blank=True, help_text='Barber biography')),
                ('photo', models.ImageField(blank=True, help_text='Barber profile photo', null=True, upload_to='barber_photos/')),
                ('rating', models.DecimalField(decimal_places=1, default=0, help_text='Average rating (0-5)', max_digits=3)),
                ('phone', models.CharField(blank=True, help_text='Barber phone number', max_length=15)),
                ('is_available', models.BooleanField(default=True, help_text='Is barber currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barber',
                'verbose_name_plural': 'Barbers',
                'db_table': 'barbers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Service name (e.g., Haircut, Beard Trim)', max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the service')),
                ('price', models.DecimalField(decimal_places=2, help_text='Service price', max_digits=10)),
                ('duration', models.PositiveIntegerField(default=30, help_text='Service duration in minutes')),
                ('image', models.ImageField(blank=True, help_text='Service image', null=True, upload_to='service_images/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this service available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(help_text='Date of the appointment')),
                ('booking_time', models.TimeField(help_text='Time of the appointment')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current booking status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(help_text='Barber assigned to this booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='barber_app.barber')),
                ('service', models.ForeignKey(help_text='Service booked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='barber_app.service')),
                ('user', models.ForeignKey(help_text='User making the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-booking_date', '-booking_time'],
                'unique_together': {('barber', 'booking_date', 'booking_time')},
            },
        ),
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(help_text='Services offered by this barber', related_name='barbers', to='barber_app.service'),
        ),
        migrations.AddField(
            model_name='barber',
            name='user',
            field=models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Rating from 1 to 5')),
                ('comment', models.TextField(help_text='Review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(help_text='Barber being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='barber_app.barber')),
                ('booking', models.OneToOneField(blank=True, help_text='Associated booking', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='barber_app.booking')),
                ('user', models.ForeignKey(help_text='User leaving the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'barber', 'booking')},
            },
        ),
    ]
