# Generated by Django 6.0 on 2026-04-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Full address', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('google_maps_url', models.URLField(blank=True, help_text='Google Maps URL for this location')),
                ('opening_time', models.TimeField(default='09:00', help_text='Opening time')),
                ('closing_time', models.TimeField(default='18:00', help_text='Closing time')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number for bookings (e.g., +1234567890)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.OneToOneField(help_text='Barber this location belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='location', to='barber_app.barber')),
            ],
            options={
                'verbose_name': 'Barber Location',
                'verbose_name_plural': 'Barber Locations',
                'db_table': 'barber_locations',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Image title or description', max_length=200)),
                ('image', models.ImageField(help_text='Gallery image', upload_to='gallery/')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the work')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this image on barber profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(help_text='Barber whose gallery this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='barber_app.barber')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery Images',
                'db_table': 'gallery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Offer title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the offer')),
                ('offer_type', models.CharField(choices=[('discount', 'Discount'), ('special', 'Special Offer'), ('bundle', 'Bundle Deal'), ('seasonal', 'Seasonal Offer')], default='discount', help_text='Type of offer', max_length=20)),
                ('discount_percent', models.PositiveIntegerField(default=0, help_text='Discount percentage (0-100)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Offer image/banner', null=True, upload_to='offers/')),
                ('start_date', models.DateField(help_text='Offer start date')),
                ('end_date', models.DateField(help_text='Offer end date')),
                ('is_active', models.BooleanField(default=True, help_text='Is this offer currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_barber', models.ForeignKey(blank=True, help_text='Barber this offer applies to (leave empty for all barbers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='barber_app.barber')),
                ('applicable_service', models.ForeignKey(blank=True, help_text='Service this offer applies to (leave empty for all services)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='barber_app.service')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
